.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel func_8002C088
    /* 1C888 8002C088 801F023C */  lui        $v0, (0x1F8000E8 >> 16)
    /* 1C88C 8002C08C E800428C */  lw         $v0, (0x1F8000E8 & 0xFFFF)($v0)
    /* 1C890 8002C090 80200400 */  sll        $a0, $a0, 2
    /* 1C894 8002C094 2BB00008 */  j          .L8002C0AC
    /* 1C898 8002C098 21204400 */   addu      $a0, $v0, $a0
    /* 1C89C 8002C09C 801F043C */  lui        $a0, (0x1F8000E8 >> 16)
    /* 1C8A0 8002C0A0 E800848C */  lw         $a0, (0x1F8000E8 & 0xFFFF)($a0)
    /* 1C8A4 8002C0A4 3000C58C */  lw         $a1, 0x30($a2)
    /* 1C8A8 8002C0A8 2C00C68C */  lw         $a2, 0x2C($a2)
  .L8002C0AC:
    /* 1C8AC 8002C0AC 31B0000C */  jal        func_8002C0C4
    /* 1C8B0 8002C0B0 00000000 */   nop
    /* 1C8B4 8002C0B4 2800BF8F */  lw         $ra, 0x28($sp)
    /* 1C8B8 8002C0B8 3000BD27 */  addiu      $sp, $sp, 0x30
    /* 1C8BC 8002C0BC 0800E003 */  jr         $ra
    /* 1C8C0 8002C0C0 00000000 */   nop
.size func_8002C088, . - func_8002C088

glabel func_8002C0C4
    /* 1C8C4 8002C0C4 B0FFBD27 */  addiu      $sp, $sp, -0x50
    /* 1C8C8 8002C0C8 21688000 */  addu       $t5, $a0, $zero
    /* 1C8CC 8002C0CC 3000B2AF */  sw         $s2, 0x30($sp)
    /* 1C8D0 8002C0D0 2190A000 */  addu       $s2, $a1, $zero
    /* 1C8D4 8002C0D4 3C00B5AF */  sw         $s5, 0x3C($sp)
    /* 1C8D8 8002C0D8 0009153C */  lui        $s5, (0x9000000 >> 16)
    /* 1C8DC 8002C0DC 4000B6AF */  sw         $s6, 0x40($sp)
    /* 1C8E0 8002C0E0 FF00163C */  lui        $s6, (0xFFFFFF >> 16)
    /* 1C8E4 8002C0E4 FFFFD636 */  ori        $s6, $s6, (0xFFFFFF & 0xFFFF)
    /* 1C8E8 8002C0E8 801F0B3C */  lui        $t3, (0x1F800100 >> 16)
    /* 1C8EC 8002C0EC 00016B35 */  ori        $t3, $t3, (0x1F800100 & 0xFFFF)
    /* 1C8F0 8002C0F0 0036023C */  lui        $v0, (0x36000000 >> 16)
    /* 1C8F4 8002C0F4 4800BEAF */  sw         $fp, 0x48($sp)
    /* 1C8F8 8002C0F8 4400B7AF */  sw         $s7, 0x44($sp)
    /* 1C8FC 8002C0FC 3800B4AF */  sw         $s4, 0x38($sp)
    /* 1C900 8002C100 3400B3AF */  sw         $s3, 0x34($sp)
    /* 1C904 8002C104 2C00B1AF */  sw         $s1, 0x2C($sp)
    /* 1C908 8002C108 2800B0AF */  sw         $s0, 0x28($sp)
    /* 1C90C 8002C10C 2000B6AF */  sw         $s6, 0x20($sp)
    /* 1C910 8002C110 0000AF91 */  lbu        $t7, 0x0($t5)
    /* 1C914 8002C114 0400AE8D */  lw         $t6, 0x4($t5)
    /* 1C918 8002C118 FF00D130 */  andi       $s1, $a2, 0xFF
    /* 1C91C 8002C11C 0000A2AF */  sw         $v0, 0x0($sp)
    /* 1C920 8002C120 00FFC230 */  andi       $v0, $a2, 0xFF00
    /* 1C924 8002C124 02820200 */  srl        $s0, $v0, 8
    /* 1C928 8002C128 02140600 */  srl        $v0, $a2, 16
    /* 1C92C 8002C12C FF005930 */  andi       $t9, $v0, 0xFF
    /* 1C930 8002C130 1000B88D */  lw         $t8, 0x10($t5)
    /* 1C934 8002C134 0C00B48D */  lw         $s4, 0xC($t5)
    /* 1C938 8002C138 0000A6CB */  lwc2       $6, 0x0($sp)
    /* 1C93C 8002C13C AB00E011 */  beqz       $t7, .L8002C3EC
    /* 1C940 8002C140 FFFF023C */   lui       $v0, (0xFFFF0000 >> 16)
    /* 1C944 8002C144 801F133C */  lui        $s3, (0x1F800070 >> 16)
    /* 1C948 8002C148 70007336 */  ori        $s3, $s3, (0x1F800070 & 0xFFFF)
    /* 1C94C 8002C14C 801F163C */  lui        $s6, (0x1F80003C >> 16)
    /* 1C950 8002C150 3C00D636 */  ori        $s6, $s6, (0x1F80003C & 0xFFFF)
    /* 1C954 8002C154 1000B6AF */  sw         $s6, 0x10($sp)
    /* 1C958 8002C158 FF000C3C */  lui        $t4, (0xFF0000 >> 16)
.size func_8002C0C4, . - func_8002C0C4
