.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel func_80099870
    /* 8A070 80099870 00000000 */  nop
.size func_80099870, . - func_80099870
