options:
  platform: psx
  basename: rock_neo
  base_path: ../
  target_path: disks/us/ROCK_NEO.EXE
  asm_path: asm/rock_neo
  asset_path: assets/rock_neo
  src_path: src/rock_neo
  compiler: GCC
  extensions_path: tools/splat_ext
  symbol_addrs_path: config/syms.us.rock_neo.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.rock_neo.txt
  undefined_syms_auto_path: config/undefined_syms_auto.us.rock_neo.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  auto_decompile_empty_functions: yes
  section_order:
    - ".rodata"
    - ".text"
    - ".data"
    # - ".sdata"
    # - ".scommon"
    # - ".bss"
    # - ".weirdassheap"
  gp_value: 0x80097864

segments:
  - [0x800, header]
  - name: main
    type: code
    start: 0x800
    vram: 0x80010000
    subalign: 4
    subsegments:
      - [0x800, rodata]
      - [0x2490, c, main]
      - [0x3BD8, c, Code800133D8]
      - [0x52C0, asm]
      - [0x5DA4, c, game]
      - [0x77D4, asm]
      - [0xA0C0, c, sound]
      - [0xBBE4, c, cd]
      - [0xE054, c, scene]
      - [0x10638, asm]
      - [0x1B3E4, c, func_8001B3E4, 0x1B4C0]
      - [0x1B4C0, c, func_8001B4C4, 0x1B4C8]
      - [0x1B4C8, c, func_8001B4CC, 0x1B638]
      - [0x1B638, c, func_8001B63C, 0x1B640]
      - [0x1B640, c, func_8001B644, 0x1B6F8]
      - [0x1B6F8, c, func_8001B6FC, 0x1B7B0]
      - [0x1B7B0, c, func_8001B858, 0x1B898]
      - [0x1B898, asm]
      - [0x1C95C, c, func_8001C95C, 0x1C9A8] # YOUR new function
      - [0x1C9A8] # The part AFTER your function
      - [0x1CAAC, c, func_8001CAAC, 0x1CB2C]
      - [0x1CB2C, c, func_8001CB7C, 0x1CC04]
      - [0x1CC04, asm]
      - [0x1D254, c, func_8001D254, 0x1D2B8]
      - [0x1D2B8, c, func_8001D2BC, 0x1D320]
      - [0x1D320, c, func_8001D324, 0x1D398]
      - [0x1D398, c, func_8001D394, 0x1D418]
      - [0x1D418, c, func_8001D414, 0x1D46C]
      - [0x1D46C, c, func_8001D468, 0x1D4C0]
      - [0x1D4C0, c, func_8001D494, 0x1D4E8]
      - [0x1D4E8, c, func_8001D58C, 0x1D5C4]
      - [0x1D5C4, asm]
      - [0x1D7E4, asm]
      - [0x2C640, c, player]
      - [0x32A38, asm]
      - [0x43F88, c, moji]
      - [0x4C710, asm]
      - [0x4F434, c, sub_scrn]
      - [0x531E0, c, debug]
      - [0x543A8, asm]
      - [0x587F8, asm, psxsdk/code]
      - [0x70EC4, data]
      - [0x80064, sdata]
      - [0x88958, scommon]
      - [0x89258, .scommon, moji]
      - [0x89260, scommon]
      - [0x8B648, bss]
      - [0xB5E88, bin] # heap?
  - [0xC9800]