.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.35.0 */

glabel D_80139F00
    /* 2D800 80139F00 0000FFFF */ .word 0xFFFF0000
    /* 2D804 80139F04 60581980 */ .word 0x80195860
    /* 2D808 80139F08 0001FFFF */ .word 0xFFFF0100
    /* 2D80C 80139F0C 90581980 */ .word 0x80195890
    /* 2D810 80139F10 00000000 */ .word 0x00000000
    /* 2D814 80139F14 00000000 */ .word 0x00000000
.size D_80139F00, . - D_80139F00
