.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.35.0 */

glabel STAGE_HED_LOAD_ADDRESS
    /* 9000 8013A000 00000000 */ .word 0x00000000
    /* 9004 8013A004 30401980 */ .word 0x80194030
    /* 9008 8013A008 00000000 */ .word 0x00000000
    /* 900C 8013A00C 00000000 */ .word 0x00000000
.size STAGE_HED_LOAD_ADDRESS, . - STAGE_HED_LOAD_ADDRESS
