.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.35.0 */

glabel D_80017800
    /* 8000 80017800 00000000 */ .word 0x00000000
    /* 8004 80017804 04004314 */ .word 0x14430004
    /* 8008 80017808 00000000 */ .word 0x00000000
.size D_80017800, . - D_80017800
