.include "macro.inc"

.section .bss

/* Generated by spimdisasm 1.35.0 */

glabel D_8009AE48
    /* 8009AE48 */ .space 0x1000

glabel D_8009BE48
    /* 8009BE48 */ .space 0x02

glabel D_8009BE4A
    /* 8009BE4A */ .space 0x02

glabel D_8009BE4C
    /* 8009BE4C */ .space 0x02

glabel D_8009BE4E
    /* 8009BE4E */ .space 0x13A

glabel D_8009BF88
    /* 8009BF88 */ .space 0x1000

glabel D_8009CF88
    /* 8009CF88 */ .space 0x01

glabel D_8009CF89
    /* 8009CF89 */ .space 0x217F

glabel D_8009F108
    /* 8009F108 */ .space 0x01

glabel D_8009F109
    /* 8009F109 */ .space 0x13

glabel D_8009F11C
    /* 8009F11C */ .space 0x3BEC

glabel D_800A2D08
    /* 800A2D08 */ .space 0x01

glabel D_800A2D09
    /* 800A2D09 */ .space 0x23F

glabel D_800A2F48
    /* 800A2F48 */ .space 0x02

glabel D_800A2F4A
    /* 800A2F4A */ .space 0x02

glabel D_800A2F4C
    /* 800A2F4C */ .space 0x02

glabel D_800A2F4E
    /* 800A2F4E */ .space 0x02

glabel D_800A2F50
    /* 800A2F50 */ .space 0x03

glabel D_800A2F53
    /* 800A2F53 */ .space 0x2F5

glabel D_800A3248
    /* 800A3248 */ .space 0x04

glabel D_800A324C
    /* 800A324C */ .space 0x04

glabel D_800A3250
    /* 800A3250 */ .space 0x04

glabel D_800A3254
    /* 800A3254 */ .space 0x04

glabel D_800A3258
    /* 800A3258 */ .space 0x04

glabel D_800A325C
    /* 800A325C */ .space 0x04

glabel D_800A3260
    /* 800A3260 */ .space 0x04

glabel D_800A3264
    /* 800A3264 */ .space 0x04

glabel D_800A3268
    /* 800A3268 */ .space 0x04

glabel D_800A326C
    /* 800A326C */ .space 0x04

glabel D_800A3270
    /* 800A3270 */ .space 0x04

glabel D_800A3274
    /* 800A3274 */ .space 0x04

glabel D_800A3278
    /* 800A3278 */ .space 0x04

glabel D_800A327C
    /* 800A327C */ .space 0x04

glabel D_800A3280
    /* 800A3280 */ .space 0x04

glabel D_800A3284
    /* 800A3284 */ .space 0x04

glabel D_800A3288
    /* 800A3288 */ .space 0x04

glabel D_800A328C
    /* 800A328C */ .space 0x04

glabel D_800A3290
    /* 800A3290 */ .space 0x04

glabel D_800A3294
    /* 800A3294 */ .space 0x04

glabel D_800A3298
    /* 800A3298 */ .space 0x04

glabel D_800A329C
    /* 800A329C */ .space 0x04

glabel D_800A32A0
    /* 800A32A0 */ .space 0x04

glabel D_800A32A4
    /* 800A32A4 */ .space 0x04

glabel D_800A32A8
    /* 800A32A8 */ .space 0x04

glabel D_800A32AC
    /* 800A32AC */ .space 0x04

glabel D_800A32B0
    /* 800A32B0 */ .space 0x04

glabel D_800A32B4
    /* 800A32B4 */ .space 0x04

glabel D_800A32B8
    /* 800A32B8 */ .space 0x04

glabel D_800A32BC
    /* 800A32BC */ .space 0x04

glabel D_800A32C0
    /* 800A32C0 */ .space 0x04

glabel D_800A32C4
    /* 800A32C4 */ .space 0x04

glabel D_800A32C8
    /* 800A32C8 */ .space 0x04

glabel D_800A32CC
    /* 800A32CC */ .space 0x04

glabel D_800A32D0
    /* 800A32D0 */ .space 0x04

glabel D_800A32D4
    /* 800A32D4 */ .space 0x04

glabel D_800A32D8
    /* 800A32D8 */ .space 0x08

glabel D_800A32E0
    /* 800A32E0 */ .space 0x100

glabel D_800A33E0
    /* 800A33E0 */ .space 0x02

glabel D_800A33E2
    /* 800A33E2 */ .space 0x02

glabel D_800A33E4
    /* 800A33E4 */ .space 0x02

glabel D_800A33E6
    /* 800A33E6 */ .space 0x02

glabel D_800A33E8
    /* 800A33E8 */ .space 0x02

glabel D_800A33EA
    /* 800A33EA */ .space 0x02

glabel D_800A33EC
    /* 800A33EC */ .space 0x02

glabel D_800A33EE
    /* 800A33EE */ .space 0x02

glabel D_800A33F0
    /* 800A33F0 */ .space 0x02

glabel D_800A33F2
    /* 800A33F2 */ .space 0x02

glabel D_800A33F4
    /* 800A33F4 */ .space 0x02

glabel D_800A33F6
    /* 800A33F6 */ .space 0x02

glabel D_800A33F8
    /* 800A33F8 */ .space 0x02

glabel D_800A33FA
    /* 800A33FA */ .space 0x03

glabel D_800A33FD
    /* 800A33FD */ .space 0x01

glabel D_800A33FE
    /* 800A33FE */ .space 0x02

glabel D_800A3400
    /* 800A3400 */ .space 0x02

glabel D_800A3402
    /* 800A3402 */ .space 0x02

glabel D_800A3404
    /* 800A3404 */ .space 0x02

glabel D_800A3406
    /* 800A3406 */ .space 0x04

glabel D_800A340A
    /* 800A340A */ .space 0x02

glabel D_800A340C
    /* 800A340C */ .space 0x02

glabel D_800A340E
    /* 800A340E */ .space 0x02

glabel D_800A3410
    /* 800A3410 */ .space 0x02

glabel D_800A3412
    /* 800A3412 */ .space 0x4DE

glabel D_800A38F0
    /* 800A38F0 */ .space 0x08

glabel D_800A38F8
    /* 800A38F8 */ .space 0x01

glabel D_800A38F9
    /* 800A38F9 */ .space 0x01

glabel D_800A38FA
    /* 800A38FA */ .space 0x01

glabel D_800A38FB
    /* 800A38FB */ .space 0x2D

glabel D_800A3928
    /* 800A3928 */ .space 0x04

glabel D_800A392C
    /* 800A392C */ .space 0x04

glabel D_800A3930
    /* 800A3930 */ .space 0x02

glabel D_800A3932
    /* 800A3932 */ .space 0x02

glabel D_800A3934
    /* 800A3934 */ .space 0x04

glabel D_800A3938
    /* 800A3938 */ .space 0x08

glabel D_800A3940
    /* 800A3940 */ .space 0x18

glabel D_800A3958
    /* 800A3958 */ .space 0x01

glabel D_800A3959
    /* 800A3959 */ .space 0x01

glabel D_800A395A
    /* 800A395A */ .space 0x01

glabel D_800A395B
    /* 800A395B */ .space 0x01

glabel D_800A395C
    /* 800A395C */ .space 0x01

glabel D_800A395D
    /* 800A395D */ .space 0x01

glabel D_800A395E
    /* 800A395E */ .space 0x01

glabel D_800A395F
    /* 800A395F */ .space 0x01

glabel D_800A3960
    /* 800A3960 */ .space 0x01

glabel D_800A3961
    /* 800A3961 */ .space 0x01

glabel D_800A3962
    /* 800A3962 */ .space 0x02

glabel D_800A3964
    /* 800A3964 */ .space 0x04

glabel D_800A3968
    /* 800A3968 */ .space 0x04

glabel D_800A396C
    /* 800A396C */ .space 0x04

glabel D_800A3970
    /* 800A3970 */ .space 0x04

glabel D_800A3974
    /* 800A3974 */ .space 0x04

glabel D_800A3978
    /* 800A3978 */ .space 0x04

glabel D_800A397C
    /* 800A397C */ .space 0x04

glabel D_800A3980
    /* 800A3980 */ .space 0x04

glabel D_800A3984
    /* 800A3984 */ .space 0x04

glabel D_800A3988
    /* 800A3988 */ .space 0x04

glabel D_800A398C
    /* 800A398C */ .space 0x04

glabel D_800A3990
    /* 800A3990 */ .space 0x04

glabel D_800A3994
    /* 800A3994 */ .space 0x04

glabel D_800A3998
    /* 800A3998 */ .space 0x04

glabel D_800A399C
    /* 800A399C */ .space 0x04

glabel D_800A39A0
    /* 800A39A0 */ .space 0x04

glabel D_800A39A4
    /* 800A39A4 */ .space 0x04

glabel D_800A39A8
    /* 800A39A8 */ .space 0x08

glabel D_800A39B0
    /* 800A39B0 */ .space 0x04

glabel D_800A39B4
    /* 800A39B4 */ .space 0x0C

glabel D_800A39C0
    /* 800A39C0 */ .space 0x04

glabel D_800A39C4
    /* 800A39C4 */ .space 0x04

glabel D_800A39C8
    /* 800A39C8 */ .space 0x08

glabel D_800A39D0
    /* 800A39D0 */ .space 0x10

glabel D_800A39E0
    /* 800A39E0 */ .space 0x04

glabel D_800A39E4
    /* 800A39E4 */ .space 0x04

glabel D_800A39E8
    /* 800A39E8 */ .space 0x08

glabel D_800A39F0
    /* 800A39F0 */ .space 0x04

glabel D_800A39F4
    /* 800A39F4 */ .space 0x04

glabel D_800A39F8
    /* 800A39F8 */ .space 0x08

glabel D_800A3A00
    /* 800A3A00 */ .space 0x10

glabel D_800A3A10
    /* 800A3A10 */ .space 0x02

glabel D_800A3A12
    /* 800A3A12 */ .space 0x02

glabel D_800A3A14
    /* 800A3A14 */ .space 0x2C

glabel D_800A3A40
    /* 800A3A40 */ .space 0x40

/* Automatically generated and unreferenced pad */
glabel D_800A3A80
    /* 800A3A80 */ .space 0xC0

glabel D_800A3B40
    /* 800A3B40 */ .space 0x01

glabel D_800A3B41
    /* 800A3B41 */ .space 0x11FF

glabel D_800A4D40
    /* 800A4D40 */ .space 0x210

glabel D_800A4F50
    /* 800A4F50 */ .space 0x7DF0

glabel D_800ACD40
    /* 800ACD40 */ .space 0x7C

glabel D_800ACDBC
    /* 800ACDBC */ .space 0x04

glabel D_800ACDC0
    /* 800ACDC0 */ .space 0x40

glabel D_800ACE00
    /* 800ACE00 */ .space 0x02

glabel D_800ACE02
    /* 800ACE02 */ .space 0x02

glabel D_800ACE04
    /* 800ACE04 */ .space 0x02

glabel D_800ACE06
    /* 800ACE06 */ .space 0x02

glabel D_800ACE08
    /* 800ACE08 */ .space 0x02

glabel D_800ACE0A
    /* 800ACE0A */ .space 0x2F6

glabel D_800AD100
    /* 800AD100 */ .space 0x40

glabel D_800AD140
    /* 800AD140 */ .space 0x02

glabel D_800AD142
    /* 800AD142 */ .space 0x02

glabel D_800AD144
    /* 800AD144 */ .space 0x02

glabel D_800AD146
    /* 800AD146 */ .space 0x02

glabel D_800AD148
    /* 800AD148 */ .space 0x02

glabel D_800AD14A
    /* 800AD14A */ .space 0x02

glabel D_800AD14C
    /* 800AD14C */ .space 0x02

glabel D_800AD14E
    /* 800AD14E */ .space 0x02

glabel D_800AD150
    /* 800AD150 */ .space 0x02

glabel D_800AD152
    /* 800AD152 */ .space 0x02

glabel D_800AD154
    /* 800AD154 */ .space 0x01

glabel D_800AD155
    /* 800AD155 */ .space 0x01

glabel D_800AD156
    /* 800AD156 */ .space 0x01

glabel D_800AD157
    /* 800AD157 */ .space 0x01

glabel D_800AD158
    /* 800AD158 */ .space 0x01

glabel D_800AD159
    /* 800AD159 */ .space 0x01

glabel D_800AD15A
    /* 800AD15A */ .space 0x02

glabel D_800AD15C
    /* 800AD15C */ .space 0x04

glabel D_800AD160
    /* 800AD160 */ .space 0x08

glabel D_800AD168
    /* 800AD168 */ .space 0x4000

glabel D_800B1168
    /* 800B1168 */ .space 0x4000

glabel D_800B5168
    /* 800B5168 */ .space 0x08

glabel D_800B5170
    /* 800B5170 */ .space 0x40

glabel Player_work
    /* 800B51B0 */ .space 0x5F4

glabel Player_work2
    /* 800B57A4 */ .space 0x5F4

glabel D_800B5D98
    /* 800B5D98 */ .space 0x02

glabel D_800B5D9A
    /* 800B5D9A */ .space 0x02

glabel D_800B5D9C
    /* 800B5D9C */ .space 0x14

glabel D_800B5DB0
    /* 800B5DB0 */ .space 0x100

glabel D_800B5EB0
    /* 800B5EB0 */ .space 0x28

glabel D_800B5ED8
    /* 800B5ED8 */ .space 0x04

glabel D_800B5EDC
    /* 800B5EDC */ .space 0x04

glabel D_800B5EE0
    /* 800B5EE0 */ .space 0x02

glabel D_800B5EE2
    /* 800B5EE2 */ .space 0x3E

glabel D_800B5F20
    /* 800B5F20 */ .space 0x10

glabel D_800B5F30
    /* 800B5F30 */ .space 0x04

glabel D_800B5F34
    /* 800B5F34 */ .space 0x04

glabel D_800B5F38
    /* 800B5F38 */ .space 0x04

glabel D_800B5F3C
    /* 800B5F3C */ .space 0x04

glabel D_800B5F40
    /* 800B5F40 */ .space 0x04

glabel D_800B5F44
    /* 800B5F44 */ .space 0x01

glabel D_800B5F45
    /* 800B5F45 */ .space 0x01

glabel D_800B5F46
    /* 800B5F46 */ .space 0x01

glabel D_800B5F47
    /* 800B5F47 */ .space 0x01

glabel D_800B5F48
    /* 800B5F48 */ .space 0x01

glabel D_800B5F49
    /* 800B5F49 */ .space 0x01

glabel D_800B5F4A
    /* 800B5F4A */ .space 0x02

glabel D_800B5F4C
    /* 800B5F4C */ .space 0x01

glabel D_800B5F4D
    /* 800B5F4D */ .space 0x01

glabel D_800B5F4E
    /* 800B5F4E */ .space 0x01

glabel D_800B5F4F
    /* 800B5F4F */ .space 0x11

glabel D_800B5F60
    /* 800B5F60 */ .space 0x10

glabel D_800B5F70
    /* 800B5F70 */ .space 0x08

glabel D_800B5F78
    /* 800B5F78 */ .space 0x08

glabel D_800B5F80
    /* 800B5F80 */ .space 0x02

glabel D_800B5F82
    /* 800B5F82 */ .space 0x0E

glabel D_800B5F90
    /* 800B5F90 */ .space 0x10

glabel D_800B5FA0
    /* 800B5FA0 */ .space 0x10

glabel D_800B5FB0
    /* 800B5FB0 */ .space 0x01

glabel D_800B5FB1
    /* 800B5FB1 */ .space 0x03

glabel D_800B5FB4
    /* 800B5FB4 */ .space 0x01

glabel D_800B5FB5
    /* 800B5FB5 */ .space 0x01

glabel D_800B5FB6
    /* 800B5FB6 */ .space 0x01

glabel D_800B5FB7
    /* 800B5FB7 */ .space 0x169

glabel D_800B6120
    /* 800B6120 */ .space 0x10

glabel D_800B6130
    /* 800B6130 */ .space 0x100

glabel D_800B6230
    /* 800B6230 */ .space 0xE00

glabel D_800B7030
    /* 800B7030 */ .space 0xA80

glabel D_800B7AB0
    /* 800B7AB0 */ .space 0x04

glabel D_800B7AB4
    /* 800B7AB4 */ .space 0x04

glabel D_800B7AB8
    /* 800B7AB8 */ .space 0x04

glabel D_800B7ABC
    /* 800B7ABC */ .space 0x04

glabel D_800B7AC0
    /* 800B7AC0 */ .space 0x04

glabel D_800B7AC4
    /* 800B7AC4 */ .space 0x04

glabel D_800B7AC8
    /* 800B7AC8 */ .space 0x02

glabel D_800B7ACA
    /* 800B7ACA */ .space 0x02

glabel D_800B7ACC
    /* 800B7ACC */ .space 0x02

glabel D_800B7ACE
    /* 800B7ACE */ .space 0x02

glabel D_800B7AD0
    /* 800B7AD0 */ .space 0x02

glabel D_800B7AD2
    /* 800B7AD2 */ .space 0x0E

glabel D_800B7AE0
    /* 800B7AE0 */ .space 0x10

glabel D_800B7AF0
    /* 800B7AF0 */ .space 0x1A0

glabel D_800B7C90
    /* 800B7C90 */ .space 0x3120

glabel D_800BADB0
    /* 800BADB0 */ .space 0x04

glabel D_800BADB4
    /* 800BADB4 */ .space 0xFC

glabel D_800BAEB0
    /* 800BAEB0 */ .space 0x80

glabel D_800BAF30
    /* 800BAF30 */ .space 0x08

glabel D_800BAF38
    /* 800BAF38 */ .space 0x780

glabel Moji_work
    /* 800BB6B8 */ .space 0x310

glabel D_800BB9C8
    /* 800BB9C8 */ .space 0xC2

glabel D_800BBA8A
    /* 800BBA8A */ .space 0x06

glabel D_800BBA90
    /* 800BBA90 */ .space 0x268

glabel D_800BBCF8
    /* 800BBCF8 */ .space 0x80

glabel D_800BBD78
    /* 800BBD78 */ .space 0x09

glabel D_800BBD81
    /* 800BBD81 */ .space 0x01

glabel D_800BBD82
    /* 800BBD82 */ .space 0x01

glabel D_800BBD83
    /* 800BBD83 */ .space 0x01

glabel D_800BBD84
    /* 800BBD84 */ .space 0x01

glabel D_800BBD85
    /* 800BBD85 */ .space 0x01

glabel D_800BBD86
    /* 800BBD86 */ .space 0x01

glabel D_800BBD87
    /* 800BBD87 */ .space 0x05

glabel D_800BBD8C
    /* 800BBD8C */ .space 0x02

glabel D_800BBD8E
    /* 800BBD8E */ .space 0x02

glabel D_800BBD90
    /* 800BBD90 */ .space 0x02

glabel D_800BBD92
    /* 800BBD92 */ .space 0x02

glabel D_800BBD94
    /* 800BBD94 */ .space 0x02

glabel D_800BBD96
    /* 800BBD96 */ .space 0x02

glabel D_800BBD98
    /* 800BBD98 */ .space 0x04

glabel D_800BBD9C
    /* 800BBD9C */ .space 0x0E

glabel D_800BBDAA
    /* 800BBDAA */ .space 0x01

glabel D_800BBDAB
    /* 800BBDAB */ .space 0x05

glabel D_800BBDB0
    /* 800BBDB0 */ .space 0x02

glabel D_800BBDB2
    /* 800BBDB2 */ .space 0x0E

glabel D_800BBDC0
    /* 800BBDC0 */ .space 0x0E

glabel D_800BBDCE
    /* 800BBDCE */ .space 0x02

glabel D_800BBDD0
    /* 800BBDD0 */ .space 0x04

glabel D_800BBDD4
    /* 800BBDD4 */ .space 0x02

glabel D_800BBDD6
    /* 800BBDD6 */ .space 0x1C

glabel D_800BBDF2
    /* 800BBDF2 */ .space 0x06

glabel D_800BBDF8
    /* 800BBDF8 */ .space 0x02

glabel D_800BBDFA
    /* 800BBDFA */ .space 0x1C

glabel D_800BBE16
    /* 800BBE16 */ .space 0x06

glabel D_800BBE1C
    /* 800BBE1C */ .space 0x02

glabel D_800BBE1E
    /* 800BBE1E */ .space 0x0E

glabel D_800BBE2C
    /* 800BBE2C */ .space 0x04

glabel D_800BBE30
    /* 800BBE30 */ .space 0x04

glabel D_800BBE34
    /* 800BBE34 */ .space 0x04

glabel D_800BBE38
    /* 800BBE38 */ .space 0x01

glabel D_800BBE39
    /* 800BBE39 */ .space 0x01

glabel D_800BBE3A
    /* 800BBE3A */ .space 0x02

glabel D_800BBE3C
    /* 800BBE3C */ .space 0x04

glabel D_800BBE40
    /* 800BBE40 */ .space 0x02

glabel D_800BBE42
    /* 800BBE42 */ .space 0x02

glabel D_800BBE44
    /* 800BBE44 */ .space 0x02

glabel D_800BBE46
    /* 800BBE46 */ .space 0x02

glabel D_800BBE48
    /* 800BBE48 */ .space 0x208

glabel D_800BC050
    /* 800BC050 */ .space 0x08

glabel D_800BC058
    /* 800BC058 */ .space 0x300

glabel D_800BC358
    /* 800BC358 */ .space 0x08

glabel D_800BC360
    /* 800BC360 */ .space 0x140

glabel D_800BC4A0
    /* 800BC4A0 */ .space 0x288

glabel D_800BC728
    /* 800BC728 */ .space 0x04

glabel D_800BC72C
    /* 800BC72C */ .space 0x04

glabel D_800BC730
    /* 800BC730 */ .space 0x03

glabel D_800BC733
    /* 800BC733 */ .space 0x05

glabel D_800BC738
    /* 800BC738 */ .space 0x01

glabel D_800BC739
    /* 800BC739 */ .space 0x07

glabel D_800BC740
    /* 800BC740 */ .space 0x04

glabel D_800BC744
    /* 800BC744 */ .space 0x04

glabel D_800BC748
    /* 800BC748 */ .space 0x08

glabel D_800BC750
    /* 800BC750 */ .space 0x04

glabel D_800BC754
    /* 800BC754 */ .space 0x04

glabel D_800BC758
    /* 800BC758 */ .space 0x18

glabel D_800BC770
    /* 800BC770 */ .space 0x04

glabel D_800BC774
    /* 800BC774 */ .space 0x04

glabel D_800BC778
    /* 800BC778 */ .space 0x08

glabel D_800BC780
    /* 800BC780 */ .space 0x04

glabel D_800BC784
    /* 800BC784 */ .space 0x04

glabel D_800BC788
    /* 800BC788 */ .space 0x28

glabel D_800BC7B0
    /* 800BC7B0 */ .space 0x04

glabel D_800BC7B4
    /* 800BC7B4 */ .space 0x04

glabel D_800BC7B8
    /* 800BC7B8 */ .space 0x18

glabel D_800BC7D0
    /* 800BC7D0 */ .space 0x04

glabel D_800BC7D4
    /* 800BC7D4 */ .space 0x04

glabel D_800BC7D8
    /* 800BC7D8 */ .space 0x08

glabel D_800BC7E0
    /* 800BC7E0 */ .space 0x04

glabel D_800BC7E4
    /* 800BC7E4 */ .space 0x04

glabel D_800BC7E8
    /* 800BC7E8 */ .space 0x08

glabel D_800BC7F0
    /* 800BC7F0 */ .space 0x04

glabel D_800BC7F4
    /* 800BC7F4 */ .space 0x04

glabel D_800BC7F8
    /* 800BC7F8 */ .space 0x20

glabel D_800BC818
    /* 800BC818 */ .space 0x01

glabel D_800BC819
    /* 800BC819 */ .space 0x01

glabel D_800BC81A
    /* 800BC81A */ .space 0x02

glabel D_800BC81C
    /* 800BC81C */ .space 0x04

glabel D_800BC820
    /* 800BC820 */ .space 0x198

glabel D_800BC9B8
    /* 800BC9B8 */ .space 0x39

glabel D_800BC9F1
    /* 800BC9F1 */ .space 0x5C

glabel D_800BCA4D
    /* 800BCA4D */ .space 0x51

glabel D_800BCA9E
    /* 800BCA9E */ .space 0x9B

glabel D_800BCB39
    /* 800BCB39 */ .space 0x0C

glabel D_800BCB45
    /* 800BCB45 */ .space 0x09

glabel D_800BCB4E
    /* 800BCB4E */ .space 0x94

glabel D_800BCBE2
    /* 800BCBE2 */ .space 0x63

glabel D_800BCC45
    /* 800BCC45 */ .space 0x70

glabel D_800BCCB5
    /* 800BCCB5 */ .space 0x39

glabel D_800BCCEE
    /* 800BCCEE */ .space 0x40

glabel D_800BCD2E
    /* 800BCD2E */ .space 0x2C

glabel D_800BCD5A
    /* 800BCD5A */ .space 0x39

glabel D_800BCD93
    /* 800BCD93 */ .space 0x33

glabel D_800BCDC6
    /* 800BCDC6 */ .space 0x4B

glabel D_800BCE11
    /* 800BCE11 */ .space 0x4C

glabel D_800BCE5D
    /* 800BCE5D */ .space 0x64

glabel D_800BCEC1
    /* 800BCEC1 */ .space 0x57

glabel D_800BCF18
    /* 800BCF18 */ .space 0x2C

glabel D_800BCF44
    /* 800BCF44 */ .space 0x0E

glabel D_800BCF52
    /* 800BCF52 */ .space 0x12

glabel D_800BCF64
    /* 800BCF64 */ .space 0x07

glabel D_800BCF6B
    /* 800BCF6B */ .space 0x34

glabel D_800BCF9F
    /* 800BCF9F */ .space 0x07

glabel D_800BCFA6
    /* 800BCFA6 */ .space 0x44

glabel D_800BCFEA
    /* 800BCFEA */ .space 0x10

glabel D_800BCFFA
    /* 800BCFFA */ .space 0x24

glabel D_800BD01E
    /* 800BD01E */ .space 0x2C

glabel D_800BD04A
    /* 800BD04A */ .space 0x2C

glabel D_800BD076
    /* 800BD076 */ .space 0x57

glabel D_800BD0CD
    /* 800BD0CD */ .space 0x40

glabel D_800BD10D
    /* 800BD10D */ .space 0x4B

glabel D_800BD158
    /* 800BD158 */ .space 0x12

glabel D_800BD16A
    /* 800BD16A */ .space 0x12

glabel D_800BD17C
    /* 800BD17C */ .space 0x12

glabel D_800BD18E
    /* 800BD18E */ .space 0x22

glabel D_800BD1B0
    /* 800BD1B0 */ .space 0x12

glabel D_800BD1C2
    /* 800BD1C2 */ .space 0x12

glabel D_800BD1D4
    /* 800BD1D4 */ .space 0x1E0

glabel D_800BD3B4
    /* 800BD3B4 */ .space 0x04

glabel D_800BD3B8
    /* 800BD3B8 */ .space 0xDFC

glabel D_800BE1B4
    /* 800BE1B4 */ .space 0x143

glabel D_800BE2F7
    /* 800BE2F7 */ .space 0x01

glabel D_800BE2F8
    /* 800BE2F8 */ .space 0x01

glabel D_800BE2F9
    /* 800BE2F9 */ .space 0x7E

glabel D_800BE377
    /* 800BE377 */ .space 0x01

glabel Sce_flag
    /* 800BE378 */ .space 0x63

glabel D_800BE3DB
    /* 800BE3DB */ .space 0x45

glabel D_800BE420
    /* 800BE420 */ .space 0x08

glabel D_800BE428
    /* 800BE428 */ .space 0x04

glabel D_800BE42C
    /* 800BE42C */ .space 0x04

glabel D_800BE430
    /* 800BE430 */ .space 0x04

glabel D_800BE434
    /* 800BE434 */ .space 0x04

glabel D_800BE438
    /* 800BE438 */ .space 0x40

glabel D_800BE478
    /* 800BE478 */ .space 0x80

glabel D_800BE4F8
    /* 800BE4F8 */ .space 0x1E0

glabel D_800BE6D8
    /* 800BE6D8 */ .space 0x400

glabel D_800BEAD8
    /* 800BEAD8 */ .space 0x4B0

glabel D_800BEF88
    /* 800BEF88 */ .space 0x190

glabel D_800BF118
    /* 800BF118 */ .space 0x01

glabel D_800BF119
    /* 800BF119 */ .space 0x9FF

glabel D_800BFB18
    /* 800BFB18 */ .space 0x04

glabel D_800BFB1C
    /* 800BFB1C */ .space 0x04

glabel D_800BFB20
    /* 800BFB20 */ .space 0x01

glabel D_800BFB21
    /* 800BFB21 */ .space 0x01

glabel D_800BFB22
    /* 800BFB22 */ .space 0x10BE

glabel D_800C0BE0
    /* 800C0BE0 */ .space 0x01

glabel D_800C0BE1
    /* 800C0BE1 */ .space 0x01

glabel D_800C0BE2
    /* 800C0BE2 */ .space 0x01

glabel D_800C0BE3
    /* 800C0BE3 */ .space 0x01

glabel D_800C0BE4
    /* 800C0BE4 */ .space 0x01

glabel D_800C0BE5
    /* 800C0BE5 */ .space 0x01

glabel D_800C0BE6
    /* 800C0BE6 */ .space 0x01

glabel D_800C0BE7
    /* 800C0BE7 */ .space 0x03

glabel D_800C0BEA
    /* 800C0BEA */ .space 0x01

glabel D_800C0BEB
    /* 800C0BEB */ .space 0x01

glabel D_800C0BEC
    /* 800C0BEC */ .space 0x01

glabel D_800C0BED
    /* 800C0BED */ .space 0x01

glabel D_800C0BEE
    /* 800C0BEE */ .space 0x01

glabel D_800C0BEF
    /* 800C0BEF */ .space 0x01

glabel D_800C0BF0
    /* 800C0BF0 */ .space 0x01

glabel D_800C0BF1
    /* 800C0BF1 */ .space 0x01

glabel D_800C0BF2
    /* 800C0BF2 */ .space 0x01

glabel D_800C0BF3
    /* 800C0BF3 */ .space 0x01

glabel D_800C0BF4
    /* 800C0BF4 */ .space 0x02

glabel D_800C0BF6
    /* 800C0BF6 */ .space 0x02

glabel D_800C0BF8
    /* 800C0BF8 */ .space 0x02

glabel D_800C0BFA
    /* 800C0BFA */ .space 0x02

glabel D_800C0BFC
    /* 800C0BFC */ .space 0x02

glabel D_800C0BFE
    /* 800C0BFE */ .space 0x02

glabel D_800C0C00
    /* 800C0C00 */ .space 0x24

glabel D_800C0C24
    /* 800C0C24 */ .space 0x02

glabel D_800C0C26
    /* 800C0C26 */ .space 0x04

glabel D_800C0C2A
    /* 800C0C2A */ .space 0x02

glabel D_800C0C2C
    /* 800C0C2C */ .space 0x02

glabel D_800C0C2E
    /* 800C0C2E */ .space 0x06

glabel D_800C0C34
    /* 800C0C34 */ .space 0x14

glabel D_800C0C48
    /* 800C0C48 */ .space 0x02

glabel D_800C0C4A
    /* 800C0C4A */ .space 0x12

glabel D_800C0C5C
    /* 800C0C5C */ .space 0x02

glabel D_800C0C5E
    /* 800C0C5E */ .space 0x08

glabel D_800C0C66
    /* 800C0C66 */ .space 0x0C

glabel D_800C0C72
    /* 800C0C72 */ .space 0x01

glabel D_800C0C73
    /* 800C0C73 */ .space 0x01

glabel D_800C0C74
    /* 800C0C74 */ .space 0x66

glabel D_800C0CDA
    /* 800C0CDA */ .space 0x14

glabel D_800C0CEE
    /* 800C0CEE */ .space 0x08

glabel D_800C0CF6
    /* 800C0CF6 */ .space 0x0C

glabel D_800C0D02
    /* 800C0D02 */ .space 0x01

glabel D_800C0D03
    /* 800C0D03 */ .space 0x01

glabel D_800C0D04
    /* 800C0D04 */ .space 0x64

glabel D_800C0D68
    /* 800C0D68 */ .space 0x26

glabel D_800C0D8E
    /* 800C0D8E */ .space 0x04

glabel D_800C0D92
    /* 800C0D92 */ .space 0x0A

glabel D_800C0D9C
    /* 800C0D9C */ .space 0x14

glabel D_800C0DB0
    /* 800C0DB0 */ .space 0x10

glabel D_800C0DC0
    /* 800C0DC0 */ .space 0x28

glabel D_800C0DE8
    /* 800C0DE8 */ .space 0x02

glabel D_800C0DEA
    /* 800C0DEA */ .space 0x02

glabel D_800C0DEC
    /* 800C0DEC */ .space 0x02

glabel D_800C0DEE
    /* 800C0DEE */ .space 0x02

glabel D_800C0DF0
    /* 800C0DF0 */ .space 0x02

glabel D_800C0DF2
    /* 800C0DF2 */ .space 0x176

glabel D_800C0F68
    /* 800C0F68 */ .space 0x2E

glabel D_800C0F96
    /* 800C0F96 */ .space 0x04

glabel D_800C0F9A
    /* 800C0F9A */ .space 0x02

glabel D_800C0F9C
    /* 800C0F9C */ .space 0x02

glabel D_800C0F9E
    /* 800C0F9E */ .space 0x1A

glabel D_800C0FB8
    /* 800C0FB8 */ .space 0x08

glabel D_800C0FC0
    /* 800C0FC0 */ .space 0x26

glabel D_800C0FE6
    /* 800C0FE6 */ .space 0x04

glabel D_800C0FEA
    /* 800C0FEA */ .space 0x02

glabel D_800C0FEC
    /* 800C0FEC */ .space 0x02

glabel D_800C0FEE
    /* 800C0FEE */ .space 0x1A

glabel D_800C1008
    /* 800C1008 */ .space 0x08

glabel D_800C1010
    /* 800C1010 */ .space 0xB00

glabel Game_work
    /* 800C1B10 */ .space 0x210

glabel D_800C1D20
    /* 800C1D20 */ .space 0x04

glabel D_800C1D24
    /* 800C1D24 */ .space 0x04

glabel D_800C1D28
    /* 800C1D28 */ .space 0x04

glabel D_800C1D2C
    /* 800C1D2C */ .space 0x17F4

glabel D_800C3520
    /* 800C3520 */ .space 0x08

glabel D_800C3528
    /* 800C3528 */ .space 0x30

glabel D_800C3558
    /* 800C3558 */ .space 0x08

glabel D_800C3560
    /* 800C3560 */ .space 0x02

glabel D_800C3562
    /* 800C3562 */ .space 0x02

glabel D_800C3564
    /* 800C3564 */ .space 0x04

glabel D_800C3568
    /* 800C3568 */ .space 0x02

glabel D_800C356A
    /* 800C356A */ .space 0x02

glabel D_800C356C
    /* 800C356C */ .space 0x01

glabel D_800C356D
    /* 800C356D */ .space 0x01

glabel D_800C356E
    /* 800C356E */ .space 0x01

glabel D_800C356F
    /* 800C356F */ .space 0x01

glabel D_800C3570
    /* 800C3570 */ .space 0x01

glabel D_800C3571
    /* 800C3571 */ .space 0x0F

glabel D_800C3580
    /* 800C3580 */ .space 0x01

glabel D_800C3581
    /* 800C3581 */ .space 0x13

glabel D_800C3594
    /* 800C3594 */ .space 0x167C

glabel Debug_work
    /* 800C4C10 */ .space 0x38

glabel Scene_work
    /* 800C4C48 */ .space 0xA8

glabel D_800C4CF0
    /* 800C4CF0 */ .space 0x80

glabel D_800C4D70
    /* 800C4D70 */ .space 0x800

glabel D_800C5570
    /* 800C5570 */ .space 0x02

glabel D_800C5572
    /* 800C5572 */ .space 0x06

glabel D_800C5578
    /* 800C5578 */ .space 0x40

glabel D_800C55B8
    /* 800C55B8 */ .space 0x08

glabel D_800C55C0
    /* 800C55C0 */ .space 0x44

glabel D_800C5604
    /* 800C5604 */ .space 0x04

glabel D_800C5608
    /* 800C5608 */ .space 0x0C

glabel D_800C5614
    /* 800C5614 */ .space 0x04

glabel D_800C5618
    /* 800C5618 */ .space 0x04

glabel D_800C561C
    /* 800C561C */ .space 0x04

glabel D_800C5620
    /* 800C5620 */ .space 0x04

glabel D_800C5624
    /* 800C5624 */ .space 0x04

glabel D_800C5628
    /* 800C5628 */ .space 0x0C

glabel D_800C5634
    /* 800C5634 */ .space 0x04

glabel D_800C5638
    /* 800C5638 */ .space 0x08

glabel D_800C5640
    /* 800C5640 */ .space 0x40

glabel D_800C5680
    /* 800C5680 */ .space 0x02

glabel D_800C5682
    /* 800C5682 */ .space 0x06
