.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.35.0 */

glabel STAGE_IDX_LOAD_ADDRESS
    /* 3000 8015C000 00000000 */ .word 0x00000000
    /* 3004 8015C004 00000000 */ .word 0x00000000
    /* 3008 8015C008 00000000 */ .word 0x00000000
.size STAGE_IDX_LOAD_ADDRESS, . - STAGE_IDX_LOAD_ADDRESS
