#!/usr/bin/env python3
"""
Fix Splat Addresses - Convert absolute addresses to relative addresses
This tool fixes the splat.yaml generated by the assembly analyzer.
"""

import re

def fix_splat_addresses():
    """Fix the splat.yaml addresses"""
    print("🔧 Fixing splat.yaml addresses...")
    
    # Read the perfect splat.yaml
    with open("perfect_splat.yaml", "r") as f:
        content = f.read()
    
    # Fix absolute addresses to relative addresses
    # Convert 0x800XXXXX to 0xXXXXX (relative to 0x800)
    fixed_content = re.sub(r'0x800([0-9a-fA-F]{5})', r'0x\1', content)
    
    # Also fix the large addresses
    fixed_content = re.sub(r'0x801([0-9a-fA-F]{7})', r'0x1\1', fixed_content)
    fixed_content = re.sub(r'0x880([0-9a-fA-F]{7})', r'0x80\1', fixed_content)
    
    # Write the fixed version
    with open("config/splat.us.rock_neo.yaml", "w") as f:
        f.write(fixed_content)
    
    print("✅ Fixed splat.yaml addresses!")
    print("📁 Saved to: config/splat.us.rock_neo.yaml")

if __name__ == "__main__":
    fix_splat_addresses()
